# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('homepage', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('telephone_number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=30)),
                ('contact_first_name', models.CharField(max_length=30)),
                ('contact_last_name', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_telephone_number', models.CharField(max_length=30)),
                ('contact_image_url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('professional_field', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('min_age', models.CharField(max_length=30)),
                ('income_per_hour', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('requirements', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=30)),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FerienJobsBoerse.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('telephone_number', models.CharField(max_length=30)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('qualifications', models.CharField(max_length=30)),
                ('wish_sector', models.CharField(max_length=30)),
            ],
        ),
    ]
