# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FerienJobsBoerse', '0002_auto_20170618_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_image_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='homepage',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='image_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
